"""Domain types for backend API tests (mirrors tests/ui-tests/src/models layout)."""

from .payments import (
    BalanceTransactionRow,
    CryptoAddressRequest,
    CryptoDepositAddressResponse,
    CryptoDepositCreatedResponse,
    CryptoDepositsListResponse,
    DepositCreatedMeta,
    DepositCrypto,
    DepositCryptoRequest,
    DepositFiat,
    DepositFiatRequest,
    DepositsListMeta,
    FiatDepositCreatedResponse,
    FiatDepositsListResponse,
    WalletBalanceRow,
)
from .trading import (
    CreateOrderRequest,
    Order,
    OrdersListMeta,
    OrdersListResponse,
)
from .user import (
    AdminRegisteredTestUser,
    RegisteredTestUser,
    UserProfile,
    UserRole,
    UserWithProfile,
    UserWithProfileTestData,
    admin_registered_test_user_from_auth_result,
    registered_test_user_from_auth_result,
)

__all__ = [
    "AdminRegisteredTestUser",
    "BalanceTransactionRow",
    "CreateOrderRequest",
    "CryptoAddressRequest",
    "CryptoDepositAddressResponse",
    "CryptoDepositCreatedResponse",
    "CryptoDepositsListResponse",
    "DepositCreatedMeta",
    "DepositCrypto",
    "DepositCryptoRequest",
    "DepositFiat",
    "DepositFiatRequest",
    "DepositsListMeta",
    "FiatDepositCreatedResponse",
    "FiatDepositsListResponse",
    "Order",
    "OrdersListMeta",
    "OrdersListResponse",
    "RegisteredTestUser",
    "WalletBalanceRow",
    "UserProfile",
    "UserRole",
    "UserWithProfile",
    "UserWithProfileTestData",
    "admin_registered_test_user_from_auth_result",
    "registered_test_user_from_auth_result",
]
